### PR TITLE
fix: @mlc-ai/web-llm is dynamically imported only when needed

### LINKED ISSUE #37: fix: large initial bundle size
The way we are currently handling instantiating the [web-llm-helper](https://github.com/addyosmani/chatty/blob/main/src/lib/web-llm-helper.ts) class is suboptimal.
It causes a large initial bundle size when the app is first rendered as seen on the image below.

(Using `next/bundle-analyzer`):
image
 
For now, this is fine as we're focusing on the desktop version for the current release. However, ideally, we would want this to be handled only when needed and not at initial render to optimize the bundle size.

### PR DESCRIPTION
**Pull request by nickytonline**
## Description

This PR reduces the initial bundle size by about 75%.

It improves the handling of [@mlc-ai/web-llm](https://www.npmjs.com/package/@mlc-ai/web-llm) dependencies via dynamic imports. This change reduces initial bundle size by only loading the package when necessary. The update includes proper type handling and error management for failed imports.

Key changes:
- Converted static imports to dynamic imports
- Implemented proper TypeScript type imports
- Added error handling for dynamic import failures
- Removed unused imports
- Optimized imports to only include required components

### Production Build Before

```
info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
 ✓ Linting    
 ✓ Collecting page data    
 ✓ Generating static pages (5/5)
 ✓ Collecting build traces    
 ✓ Finalizing page optimization    

Route (app)                              Size     First Load JS
┌ ○ /                                    385 B          2.19 MB
├ ○ /_not-found                          879 B          94.5 kB
└ ƒ /c/[id]                              472 B          2.19 MB
+ First Load JS shared by all            93.6 kB
  ├ chunks/7023-541e97237a143355.js      31.6 kB
  ├ chunks/fd9d1056-2354210a8a73cbb0.js  53.6 kB
  └ other shared chunks (total)          8.39 kB


○  (Static)   prerendered as static content
ƒ  (Dynamic)  server-rendered on demand
```

### Production Build After

```
info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
 ✓ Linting    
 ✓ Collecting page data    
 ✓ Generating static pages (5/5)
 ✓ Collecting build traces    
 ✓ Finalizing page optimization    

Route (app)                              Size     First Load JS
┌ ○ /                                    385 B           558 kB
├ ○ /_not-found                          879 B          94.6 kB
└ ƒ /c/[id]                              472 B           559 kB
+ First Load JS shared by all            93.7 kB
  ├ chunks/7023-541e97237a143355.js      31.6 kB
  ├ chunks/fd9d1056-2354210a8a73cbb0.js  53.6 kB
  └ other shared chunks (total)          8.42 kB


○  (Static)   prerendered as static content
ƒ  (Dynamic)  server-rendered on demand
```

## Screenshots and Recordings

CleanShot 2025-01-26 at 11 50 27

## Related Tickets & Documents

Closes #37

### CODE REVIEW

File: src/lib/types.d.ts [hunk 1]
```diff
@@ -1,4 +1,4 @@
-import { ChatCompletionMessageParam, ChatCompletionAssistantMessageParam, ChatCompletionUserMessageParam } from "@mlc-ai/web-llm";
+import type { ChatCompletionMessageParam, ChatCompletionAssistantMessageParam, ChatCompletionUserMessageParam } from "@mlc-ai/web-llm";
```
Comment (nickytonline) [inline src/lib/types.d.ts:1]: using `import type` so it's only for type checking and not part of the actual imports

File: src/lib/web-llm-helper.ts [hunk 2]
```diff
@@ -1,52 +1,64 @@
 // https://github.com/mlc-ai/web-llm/blob/main/examples/get-started-web-worker
 
 import useChatStore from "@/hooks/useChatStore";
-import * as webllm from "@mlc-ai/web-llm";
 import { Model } from "./models";
 import { Document } from "@langchain/core/documents";
 import { getEmbeddingsInstance } from "./embed";
+import type { AppConfig, MLCEngineInterface, InitProgressReport, CreateWebWorkerMLCEngine} from "@mlc-ai/web-llm";
```
Comment (nickytonline) [inline src/lib/web-llm-helper.ts:7]: using `import type` so it's only for type checking and not part of the actual imports

**Comment by jakobhoeg** [comment]
LGTM! 75% decrease in bundle size is such a great improvement!
Thank you so much for the PR @nickytonline
